#!/usr/bin/env sh
# Installs the VibeAround-managed Node.js runtime under
# $STARTKIT_HOME/runtime/node, mirroring what the daemon reads back:
#   versions/<version>/   the extracted release
#   current.json          the manifest the daemon treats as "installed"
#   current.env           the same facts for shell consumers
#
# Progress is streamed as NDJSON; the last JSON line is the result.
set -eu

json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

progress() {
  printf '{"event":"progress","message":"%s"}\n' "$(json_escape "$1")"
}

fail() {
  printf '{"event":"result","status":"error","message":"%s","actions":["install"]}\n' \
    "$(json_escape "$1")"
  exit 0
}

# This installer only owns the VibeAround-managed copy. When the user chose the
# system toolchain, installing Node.js is theirs to do.
if [ "${STARTKIT_PORTABLE_TOOLCHAIN:-false}" != "true" ]; then
  printf '{"event":"result","status":"blocked","message":"VibeAround'"'"'s portable toolchain is off, so Node.js has to be installed on this computer.","actions":["manual","verify"]}\n'
  exit 0
fi

runtime_dir="${STARTKIT_HOME:?STARTKIT_HOME is required}/runtime/node"
versions_dir="$runtime_dir/versions"
cache_dir="${STARTKIT_CACHE_DIR:-$runtime_dir/cache}"
index_url="${STARTKIT_NODE_INDEX_URL:-https://nodejs.org/dist/index.json}"
dist_base="${STARTKIT_NODE_DIST_BASE:-https://nodejs.org/dist}"
min_version="${STARTKIT_MIN_VERSION:-22.0.0}"
mkdir -p "$versions_dir" "$cache_dir"

case "$(uname -m)" in
  arm64|aarch64) platform="darwin-arm64" ;;
  x86_64|amd64) platform="darwin-x64" ;;
  *) fail "Unsupported macOS architecture: $(uname -m)" ;;
esac

# index.tab carries the same releases as index.json in tab-separated columns
# (1=version, 10=LTS codename, "-" when not LTS), newest first, so awk can pick
# the newest qualifying LTS without parsing JSON in the shell.
progress "Resolving the latest Node.js LTS release"
index_url_tab="$(printf '%s' "$index_url" | sed 's/index\.json$/index.tab/')"
index_file="$cache_dir/node-index.tab"
curl -fsSL "$index_url_tab" -o "$index_file" || fail "Failed to download the Node.js version index."

min_major="$(printf '%s' "$min_version" | sed 's/^v//' | cut -d. -f1)"
version="$(
  awk -F'\t' -v min_major="$min_major" '
    NR > 1 && $10 != "-" && $10 != "" {
      major = $1
      sub(/^v/, "", major)
      sub(/\..*/, "", major)
      if ((major + 0) >= (min_major + 0)) {
        print $1
        exit
      }
    }
  ' "$index_file"
)"
[ -n "$version" ] || fail "Could not resolve a Node.js LTS release at or above $min_version."

install_dir="$versions_dir/$(printf '%s' "$version" | sed 's/[^A-Za-z0-9._-]/_/g')"
node_bin="$install_dir/bin/node"

if [ -x "$node_bin" ]; then
  installed="$("$node_bin" --version 2>/dev/null || printf '')"
  if [ "$installed" = "$version" ]; then
    write_state=skip
  fi
fi

if [ "${write_state:-}" != "skip" ]; then
  archive_name="node-$version-$platform.tar.gz"
  archive_path="$cache_dir/$archive_name"

  progress "Downloading Node.js $version"
  curl -fsSL "$dist_base/$version/$archive_name" -o "$archive_path" \
    || fail "Failed to download $archive_name."

  # Node publishes SHASUMS256.txt next to the archives; verifying it is the only
  # thing standing between a hijacked mirror and an executed binary.
  progress "Verifying the Node.js archive"
  sums_path="$cache_dir/SHASUMS256-$version.txt"
  curl -fsSL "$dist_base/$version/SHASUMS256.txt" -o "$sums_path" \
    || fail "Failed to download SHASUMS256.txt for $version."
  expected="$(awk -v name="$archive_name" '$2 == name { print $1; exit }' "$sums_path")"
  [ -n "$expected" ] || fail "No checksum published for $archive_name."
  actual="$(shasum -a 256 "$archive_path" | cut -d' ' -f1)"
  if [ "$actual" != "$expected" ]; then
    rm -f "$archive_path"
    fail "Checksum mismatch for $archive_name: expected $expected, got $actual."
  fi

  progress "Extracting Node.js $version"
  staging_dir="$versions_dir/.staging-node"
  rm -rf "$staging_dir"
  mkdir -p "$staging_dir"
  tar -xzf "$archive_path" -C "$staging_dir" --strip-components=1 \
    || fail "Failed to extract $archive_name."
  [ -x "$staging_dir/bin/node" ] || fail "$archive_name did not contain bin/node."

  rm -rf "$install_dir"
  mv "$staging_dir" "$install_dir" || fail "Failed to move Node.js into $install_dir."
  rm -f "$archive_path"
fi

# The shell mirror lands before the manifest, because the manifest is what marks
# the tool as installed.
progress "Recording the Node.js runtime"
tmp_env="$runtime_dir/current.env.tmp"
{
  printf '# Generated by VibeAround. Do not edit; regenerated on every install.\n'
  printf "VA_TOOL='node'\n"
  printf "VA_TOOL_VERSION='%s'\n" "$version"
  printf "VA_TOOL_INSTALL_DIR='%s'\n" "$install_dir"
  printf "VA_TOOL_BIN_DIR='%s'\n" "$install_dir/bin"
} > "$tmp_env"
mv "$tmp_env" "$runtime_dir/current.env"

tmp_json="$runtime_dir/current.json.tmp"
printf '{\n  "version": "%s",\n  "install_dir": "%s",\n  "installed_at_unix_ms": %s\n}\n' \
  "$(json_escape "$version")" \
  "$(json_escape "$install_dir")" \
  "$(( $(date +%s) * 1000 ))" > "$tmp_json"
mv "$tmp_json" "$runtime_dir/current.json"

printf '{"event":"result","status":"ok","version":"%s","path":"%s","message":"Node.js %s is ready","actions":[]}\n' \
  "$(json_escape "$version")" "$(json_escape "$node_bin")" "$(json_escape "$version")"
